#define _GNU_SOURCE
#include "../include/localhost_http_server.h"
#include <netinet/in.h>
#include <poll.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/poll.h>
#include <sys/socket.h>
#include <uchar.h>
#include <unistd.h>

static atomic_bool server_continue = false;
static int_least32_t server_fd = -1;
static pthread_t server_thread; // NOLINT(misc-include-cleaner)

enum serverConstants {
    PORT = 8080,
    BUFFER_SIZE = 4096,
    CONNECTION_BACKLOG = 10,
    HEADER_BUFFER_SIZE = 256,
};

/* Basic http server on localhost that serves a single file.
 * Because this is just additional infrastructure to facilitate testing, I did not bother writing the original thing myself; it was generated by an
 * LLM.
 * I then made fairly significant structural changes to the output, including multithreading it for usage in a single testing binary.
 */

// cppcheck-suppress constParameterCallback; I'm not dealing with this
static void *serverMainThread(void *pHtml_file) {
    const char *const pPath = (const char *const)pHtml_file;

    char8_t buffer[BUFFER_SIZE];

    // printf("Server running at http://localhost:%d\n", PORT);

    while (atomic_load(&server_continue)) {
        // The listening socket is created once in startTestServer before this thread is spawned, and is only closed in stopTestServer after this
        // thread has been joined, so it stays valid for the whole loop. It is deliberately never reassigned here so stopTestServer always shuts
        // down and closes the right fd.
        const int_least32_t listen_fd = server_fd;
        if (listen_fd == -1) {
            break;
        }

        struct pollfd poll_fd = {listen_fd, POLLIN, 0}; // NOLINT(misc-include-cleaner)
        constexpr int_least32_t wait_millis_for_event = 100;
        if (poll(&poll_fd, 1, wait_millis_for_event) <= 0) { // NOLINT(misc-include-cleaner)
            continue;
        }
        if ((poll_fd.revents & (POLLNVAL | POLLERR | POLLHUP)) != 0) {
            if (!atomic_load(&server_continue)) {
                break;
            }
            continue;
        }

        int_least32_t client_fd;
        client_fd = accept4(listen_fd, nullptr, nullptr, SOCK_CLOEXEC);
        if (client_fd < 0) {
            if (!atomic_load(&server_continue)) {
                break;
            }
            continue;
        }

        // flawfinder: ignore. buffer is fixed size and read contains a bounds check.
        const int_least64_t bytes_read = read(client_fd, buffer, sizeof(buffer) - 1);
        if (bytes_read <= 0) {
            close(client_fd);
            continue;
        }

        buffer[(size_t)bytes_read] = '\0';

        // flawfinder: ignore. This is a contant file.
        FILE *const pFile = fopen(pPath, "rbe");

        if (!pFile) {
            constexpr int_least32_t file_not_found_response_len = 99;
            const char8_t *pResponse = u8"HTTP/1.1 404 Not Found\r\n"
                                       u8"Content-Type: text/plain\r\n"
                                       u8"Content-Length: 9\r\n"
                                       u8"Connection: close\r\n"
                                       u8"\r\n"
                                       u8"Not Found";

            write(client_fd, pResponse, strnlen((const char *const)pResponse, file_not_found_response_len + 1));
            // The connection must be closed so the client sees EOF and exits. Otherwise popen'd clients hang forever, and because they inhereit our
            // fds they keep the listen port alive even after this process is killed.
            close(client_fd);
        } else {
            int_least32_t fseek_rc = fseek(pFile, 0, SEEK_END);
            if (fseek_rc != 0) {
                perror("fseek failed.");
                (void)fclose(pFile);
                close(client_fd);
                continue;
            }

            const int_least64_t size = ftell(pFile);

            fseek_rc = fseek(pFile, 0, SEEK_SET);
            if (fseek_rc != 0) {
                perror("fseek failed.");
                (void)fclose(pFile);
                close(client_fd);
                continue;
            }

            char8_t header[HEADER_BUFFER_SIZE];
            // flawfinder: ignore. The format is constant.
            const int_least32_t header_len = snprintf((char *)header, sizeof(header),
                                                      "HTTP/1.1 200 OK\r\n"
                                                      "Content-Type: text/html\r\n"
                                                      "Content-Length: %ld\r\n"
                                                      "Connection: close\r\n"
                                                      "\r\n",
                                                      size);
            if (header_len <= 0 || header_len >= (int_least32_t)sizeof(header)) {
                perror("snprintf failed.");
                (void)fclose(pFile);
                close(client_fd);
                continue;
            }

            write(client_fd, header, (uint_least32_t)header_len);

            uint_least64_t chunk;
            [[clang::suppress]] // I am not dealing with the clang-analyzer-unix.Stream errors for this test thing
            // flawfinder: ignore. Only used locally for testing purposes, so not concerned about filtering the buffer.
            while ((chunk = fread(buffer, 1, sizeof(buffer), pFile)) > 0) {
                write(client_fd, buffer, chunk);
            }

            (void)fclose(pFile);
            close(client_fd);
        }
    }
    return nullptr;
}

int_least32_t startTestServer(char8_t *const restrict pHtml_file) {
    if (server_fd != -1) {
        stopTestServer();
    }

    // SOCK_CLOEXEC is essential: the unit tests spawn curl via popen, and without it every curl child inherits a copy of the listening socket across
    // exec. Those orphaned children then keep port 8080 bound after this process exits or restarts, causing bind to fail with "Address already in
    // use".
    const int_least32_t socket_fd = socket(AF_INET, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (socket_fd == -1) {
        perror("Socket init in startTestServer failed.");
        return -1;
    }

    const int_least32_t opt = 1;
    setsockopt(socket_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)); // NOLINT(misc-include-cleaner)

    struct sockaddr_in addr = {.sin_family = AF_INET, .sin_addr.s_addr = htonl(INADDR_LOOPBACK), .sin_port = htons(PORT)};
    if (bind(socket_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("bind in startTestServer failed.");
        close(socket_fd);
        return -1;
    }

    if (listen(socket_fd, CONNECTION_BACKLOG) < 0) {
        perror("listen in startTestServer failed.");
        close(socket_fd);
        return -1;
    }

    server_fd = socket_fd;
    atomic_store(&server_continue, true);
    if (pthread_create(&server_thread, nullptr, serverMainThread, pHtml_file) != 0) {
        perror("pthread_create in startTestServer failed.");
        atomic_store(&server_continue, false);
        close(socket_fd);
        server_fd = -1;
        return -1;
    }

    return 0;
}

void stopTestServer(void) {
    if (server_fd == -1) {
        atomic_store(&server_continue, false);
        return;
    }
    atomic_store(&server_continue, false);
    // shutdown wakes a thread blocked in poll/accept; errors (e.g. already closed) are harmless here.
    shutdown(server_fd, SHUT_RDWR);
    pthread_join(server_thread, nullptr);
    close(server_fd);
    server_fd = -1;
}
