// Copyright [2026] Ethan Heckart
#ifndef WIKICYCLE_SRC_INCLUDE_RETURNCODES_H_
#define WIKICYCLE_SRC_INCLUDE_RETURNCODES_H_

enum creationFailureRC { EMPTY_BUCKET_RC = 8, MALLOC_FAILURE_RC = 9 };
enum curlFailureRC { CURL_INIT_FAILURE_RC = 8, CURL_PERFORM_FAILURE_RC = 9 };
enum insertionRC { SUCCESSFUL_NODE_INSERTION = 0, DUPLICATE_NODE_INSERTION = 1, INSERTION_COLLISION = 2 };

#endif // WIKICYCLE_SRC_INCLUDE_RETURNCODES_H_
